name: Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18"] # You can update to '20' if your project is compatible

    permissions:
      contents: write # Needed for deployment to gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Create .nojekyll file
        run: touch .nojekyll

      - name: Install dependencies
        run: npm ci || npm install # Falls back to npm install if npm ci fails

      - name: Build site
        run: npx @11ty/eleventy --pathprefix="${{ github.repository }}"
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # The folder containing your built site
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true # Automatically remove deleted files from the deploy branch
